src/Entity/UserTask.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserTaskRepository")
 */
class UserTask
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="User", inversedBy="userTasks")
     *
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity="Task", inversedBy="userTasks",cascade={"remove"})
     *
     */
    private $task;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_creator;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_approved;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?user
    {
        return $this->user;
    }

    public function setUser(?user $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getTask(): ?task
    {
        return $this->task;
    }

    public function setTask(?task $task): self
    {
        $this->task = $task;

        return $this;
    }

    public function getIsCreator(): ?bool
    {
        return $this->is_creator;
    }

    public function setIsCreator(bool $is_creator): self
    {
        $this->is_creator = $is_creator;

        return $this;
    }

    public function getIsApproved(): ?bool
    {
        return $this->is_approved;
    }

    public function setIsApproved(bool $is_approved): self
    {
        $this->is_approved = $is_approved;

        return $this;
    }

    public function __construct()
    {
        $this->setIsCreator(true);

    }


}

src/Front/Form/RemainderType.php
<?php

namespace App\Front\Form;

use App\Common\Entity\Remainder;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class RemainderType
 * @package App\Front\Form
 */
class RemainderType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('rememberDate');

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Remainder::class,
            'allow_add' => true,
            'multiple' => true, 'prototype' => true,
            'prototype_data' => 'New Tag Placeholder',

        ]);
    }
}

src/Front/Form/TaskType.php
<?php

namespace App\Front\Form;

use App\Common\Entity\Task;
use App\Common\Entity\UserTask;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;



class TaskType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        $builder
            ->add('title', TextType::class)
            ->add('description', TextAreaType::class)
            ->add('startHour', DateTimeType::class,[
                'widget' => 'choice',
                'years'=>range(date('y'),date('y')+50),
                'months'=>range(date('m'),12),
                'days'=>range(date('d'),31)])
            ->add('endHour', DateTimeType::class,[
                'widget' => 'choice',
                'years'=>range(date('y'),date('y')+50),
                'months'=>range(date('m'),12),
                'days'=>range(date('d'),31)])
            ->add('remainders', CollectionType::class, [
                'entry_type' => RemainderType::class,
                'allow_add' => true,
                'prototype' => true,
                'by_reference' => false,
                'label' => false])
            ->add('userTasks', CollectionType::class, [
                'entry_type' => UserTaskType::class,
                'allow_add' => true,
                'prototype' => true,
                'by_reference' => false,
                'label' => false])
            ->addEventListener(FormEvents::SUBMIT, function (FormEvent $event) {

                $form = $event->getForm();
                /** @var Task $task */
                $task = $form->getData();

                $userTask = new UserTask();
                $userTask
                    ->setIsCreator(true)
                    ->setTask($task)
                    ->setIsApproved(true)
                    ->setUser($currentUser=$form->getConfig()->getOption('user'));

                $task->addUserTask($userTask);


            });
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Task::class,
            "allow_extra_fields" => true,
            'user'=>null
        ]);
    }
}

src/Front/Form/UserTaskType.php
<?php

namespace App\Front\Form;

use App\Common\Entity\UserTask;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserTaskType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('user')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => UserTask::class,
            'allow_add' => true,
            'allow delete'=>true,
            'multiple'=>true,

        ]);
    }
}

src/Front/Form/UserType.php
<?php

namespace App\Front\Form;

use App\Common\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('username')
            ->add('usernameCanonical')
            ->add('email')
            ->add('emailCanonical')
            ->add('enabled')
            ->add('salt')
            ->add('password')
            ->add('lastLogin')
            ->add('confirmationToken')
            ->add('passwordRequestedAt')
            ->add('roles')
            ->add('tasks')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Front/Controller/HomeController.php
<?php

namespace App\Front\Controller;


use App\Common\Repository\TaskRepository;
use App\Common\Repository\UserRepository;
use App\Common\Repository\UserTaskRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


class HomeController extends AbstractController
{
    /**
     * @param $first_day
     * @param UserTaskRepository $UserTaskRepository
     * @param UserRepository $userRepository
     * @return Response
     */
    public function home($first_day, UserTaskRepository $UserTaskRepository, UserRepository $userRepository): Response
    {

        $connectedUser = $this->getUser();
        $role = "ROLE_SUPER_ADMIN";


        $adminTasks = $userRepository->findByRole($role);
        return $this->render('home/index.html.twig', [

            'first_day' => $first_day,
            'selectprime' => $UserTaskRepository->findBy(['user' => $connectedUser]),
            'adminTasks' => $UserTaskRepository->findBy(['user' => $adminTasks]),
            'notApproved' => $UserTaskRepository->findBy(['user' => $connectedUser,'isApproved' => false]),




        ]);
    }

    /**
     * @param TaskRepository $task
     * @param UserTaskRepository $UserTaskRepository
     * @param UserRepository $userRepository
     * @return Response
     */
    public function index(TaskRepository $task, UserTaskRepository $UserTaskRepository, UserRepository $userRepository): Response
    {
        $connectedUser = $this->getUser();
        $role = "ROLE_SUPER_ADMIN";
        $firstDay = time();

        return $this->render('home/index.html.twig', [
            'controller_name' => 'HomeController',

            'first_day' => $firstDay,
            'select' => $task->findAll(),
            'selectprime' => $UserTaskRepository->findBy(['user' => $connectedUser]),
            'adminTasks' => $userRepository->findBy(['roles' => $role]),
            'notApproved' => $UserTaskRepository->findBy(['user' => $connectedUser,'isApproved' => false]),



        ]);
    }


}

src/Front/Controller/TaskController.php
<?php

namespace App\Front\Controller;
use DateTime;
use App\Common\Entity\Task;
use App\Front\Form\TaskType;
use App\Service\EmailGenerator;
use App\Common\Repository\UserTaskRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


/**
 * Class TaskController
 * @package App\Front\Controller
 */
class TaskController extends AbstractController
{
    /**
     * @param Request $request
     * @param EmailGenerator $message
     * @return Response
     */
    public function newTaskFront(Request $request, EmailGenerator $message): Response
    {
        $task = new Task();
        $form = $this->createForm(TaskType::class, $task, ['user' => $this->getUser()]);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($task);
            $entityManager->flush();

            foreach ($task->getUserTasks()->getValues() as $value) {
                $message->sendEmail('test sujet', $this->render('emails/NewTask.html.twig', ['task' => $task, 'usertask' => $value]), $value->getUser()->getEmail());

            }

            return $this->redirectToRoute('user_index');
        }

        return $this->render('front/new.html.twig', [
            'task' => $task,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @param Request $request
     * @param Task $task
     * @param $usertask
     * @param UserTaskRepository $UserTaskRepository
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|Response
     */
    public function changeApprove(Request $request, Task $task, $usertask, UserTaskRepository $UserTaskRepository)
    {
        $form1 = $this->createFormBuilder()
            ->add('isApproved', ChoiceType::class, [
                'choices' => [
                    'Maybe' => null,
                    'Yes' => true,
                    'No' => false,
                ],
            ])
            ->add('send', SubmitType::class)
            ->getForm();

        $form1->handleRequest($request);

        if ($form1->isSubmitted() && $form1->isValid()) {
            dump($usertask);
            $x = $UserTaskRepository->find($usertask);
            $x->setIsApproved($form1['isApproved']->getData());
            dump($task);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($x);
            $entityManager->flush();
            return $this->redirectToRoute('user_index');

        }
        return $this->render('emails/approve.html.twig', [
            'form1' => $form1->createView(),
            'task' => $task,

        ]);

    }


    /**
     * @param $day
     * @param $month
     * @param $year
     * @param Request $request
     * @param EmailGenerator $message
     * @return Response
     * @throws \Exception
     */

    public function newTaskByDay($day, $month, $year, Request $request, EmailGenerator $message): Response
    {

        $dateTime = new DateTime($year . '-' . $month . '-' . $day);

        $task = new Task();
        $task->setStarthour($dateTime);
        $task->setEndhour($dateTime);

        $form = $this->createForm(TaskType::class, $task, ['user' => $this->getUser()]);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($task);
            $entityManager->flush();
            foreach ($task->getUserTasks()->getValues() as $value) {
                $message->sendEmail('test sujet', $this->render('emails/NewTask.html.twig', ['task' => $task, 'usertask' => $value]), $value->getUser()->getEmail());

            }

            return $this->redirectToRoute('user_index');
        }
        return $this->render('home/day.html.twig', [

            'day' => $day,
            'month' => $month,
            'year' => $year,
            'task' => $task,
            'date' => $dateTime,
            'form' => $form->createView()


        ]);
    }


    public function taskByDay($day, $month, $year, UserTaskRepository $UserTaskRepository): Response
    {

        $dateTime = new DateTime($year . '-' . $month . '-' . $day);

        $connectedUser = $this->getUser();

        return $this->render('front/allTasks.html.twig', [

            'day' => $day,
            'month' => $month,
            'year' => $year,
            'tasks' => $UserTaskRepository->findBy(['user' => $connectedUser]),
            'date' => $dateTime,


        ]);
    }


    /**
     * @param Task $task
     * @param UserTaskRepository $UserTaskRepository
     * @return Response
     */
    public function show(Task $task, UserTaskRepository $UserTaskRepository): Response
    {
        $connectedUser = $this->getUser();

        return $this->render('front/show.html.twig', [
            'task' => $task,
            'selectprime' => $UserTaskRepository->findBy(['user' => $connectedUser])

        ]);
    }

    /**
     * @param Request $request
     * @param Task $task
     * @return Response
     */
    public function edit(Request $request, Task $task): Response
    {
        $form = $this->createForm(TaskType::class, $task);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('user_index', [
                'id' => $task->getId(),
            ]);
        }

        return $this->render('front/edit.html.twig', [
            'task' => $task,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @param Request $request
     * @param Task $task
     * @return Response
     */
    public function delete(Request $request, Task $task): Response
    {
        if ($this->isCsrfTokenValid('delete' . $task->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($task);
            $entityManager->flush();
        }

        return $this->redirectToRoute('user_index');
    }
}

templates/front/_delete_form.html.twig
<form method="post" action="{{ path('user_front_delete', {'id': task.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ task.id) }}">
    <button class="btn">{% trans %}Delete{% endtrans %}</button>
</form>

templates/front/_form.html.twig
{% extends 'form.html.twig' %}

{% block body %}
    <a href="{{ path('user_index') }}" class="float-left"> <i style="font-size: 30px;margin-left: 50px;margin-top: 50px;" class="fas fa-arrow-left"></i> </a>

    <div class="container-contact100">

        <div class="wrap-contact100">
            {{ form_start(form, {attr: {class: 'contact100-form validate-form'} }) }}
            <div> {{ form_row(form.title, {attr: {class: 'wrap-input100 validate-input bg1'} }) }}</div>
            <div> {{ form_row(form.description, {attr: {class: 'wrap-input100 validate-input bg1'} }) }}</div>
            <div> {{ form_row(form.startHour, {attr: {class: 'input100 js-datepicker'} }) }}</div>
            <div>{{ form_row(form.endHour, {attr: {class: 'input100 js-datepicker'} }) }}</div>
            <div class="wrap-input100 input100-select bg1">

                <ul id="email-fields-list"
                    data-prototype="{{ form_widget(form.remainders.vars.prototype, {attr: {class: 'wrap-input100 input100-select bg1'} })|e }}"
                    data-widget-tags="{{ '<li></li>'|e }}"
                    data-widget-counter="{{ form.children|length }}">
                    {% for emailField in form.remainders %}
                        <li>
                            {{ form_errors(emailField) }}
                            {{ form_widget(emailField, {attr: {class: 'wrap-input100 input100-select bg1'} }) }}
                        </li>
                    {% endfor %}
                </ul>
                <button type="button"
                        class="add-another-collection-widget btn btn-outline-dark "
                        data-list-selector="#email-fields-list">Add another date
                </button>
            </div>
            <div class="wrap-input100 input100-select bg1">


                <ul id="user-fields-list"
                    data-prototype="{{ form_widget(form.userTasks.vars.prototype, {attr: {class: 'wrap-input100 input100-select bg1'} })|e }}"
                    data-widget-tags="{{ '<li></li>'|e }}"
                    data-widget-counter="{{ form.children|length }}">
                    {% for emailField in form.userTasks %}
                        <li>
                            {{ form_errors(emailField) }}
                            {{ form_widget(emailField, {attr: {class: 'wrap-input100 input100-select bg1'} }) }}
                        </li>
                    {% endfor %}
                </ul>
                <button type="button"
                        class="add-another-collection btn btn-outline-dark "
                        data-list-selector="user-fields-list">Add another user
                </button>
            </div>


            <button class="contact100-form-btn">{{ button_label|default('Save') }}</button>
        </div>
    </div>
    {{ form_end(form) }}
{% endblock %}

templates/front/allTasks.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    {% set dateNow =  month  ~'/'~ day  ~'/'~  year %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{{ asset('vendor/bootstrap/css/bootstrap.min.css') }}"/>
    <link rel="stylesheet" href="{{ asset('fonts/font-awesome-5.9.0/css/all.css') }}"/>

    <link rel="stylesheet" href="{{ asset('vendor/animate/animate.css') }}"/>
    <link rel="stylesheet" href="{{ asset('vendor/select2/select2.min.css') }}"/>
    <link rel="stylesheet" href="{{ asset('vendor/perfect-scrollbar/perfect-scrollbar.css') }}"/>
    <link rel="stylesheet" href="{{ asset('css/FrontTasksUtil.css') }}"/>
    <link rel="stylesheet" href="{{ asset('css/FrontTasksMain.css') }}"/>
    <link rel="stylesheet" href="{{ asset('css/style.css') }}"/>






    <div class="table100 ver5 m-b-110">
        <div class="table100-head">
            <table>
                <thead>
                <tr class="row100 head">
                    <th class="cell100 column1">Task</th>
                    <th class="cell100 column2">description</th>
                    <th class="cell100 column3">Hours</th>
                    <th class="cell100 column4">action</th>


                </tr>
                </thead>
            </table>
        </div>

        <div class="table100-body js-pscroll">
            <table>
                <tbody>
                {% for i in tasks %}
                    {% if i.task.startHour|date("Y-m-d") ==dateNow|date("Y-m-d") %}
                        <tr class="row100 body">
                            <td class="cell100 column1">{{ i.task.title }}</td>
                            <td class="cell100 column2">{{ i.task.description }}</td>

                            <td class="cell100 column3">{{ i.task.startHour|date("H:i") }}
                                --{{ i.task.endHour|date("H:i") }}</td>
                            <td class="cell100 column4"><a
                                        href="{{ path('user_front_show', {'id': i.task.id}) }}">show</a><br></td>
                        </tr>
                    {% endif %}
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
    </div>
    </div>
    </div>



{% endblock body %}

templates/front/edit.html.twig
{% form_theme form 'bootstrap_4_layout.html.twig' %}


{% block body %}

  <div class="col" s >  {{ include('front/_form.html.twig', {'button_label': 'Update'}) }}</div>
    <div class="col"> {{ include('front/_delete_form.html.twig') }}</div>


   <div class="col"> <a href="{{ path('user_index') }}">{% trans %}back to list{% endtrans %}</a></div>
    </div>

{% endblock %}

templates/front/new.html.twig
{% form_theme form 'bootstrap_4_layout.html.twig' %}


{% block body %}

    {{ include('front/_form.html.twig') }}

{% endblock %}
{% block javascripts %}

    <script>

        jQuery(document).ready(function() {
            $('.js-datepicker').datetimepicker();
        });
    </script>
{% endblock %}

templates/front/show.html.twig
{% extends 'baseFront.html.twig' %}

{% block body %}
    <link rel="stylesheet" href="{{ asset('css/show.css') }}"/>

    {#start new template#}
    <div class="limiter">
        <a href="{{ path('user_index') }}">   <i style="font-size: 30px;margin-left: 50px;margin-top: 50px;" class="fas fa-arrow-left"></i> </a>

        <div class="container-table100">
            <div class="wrap-table100">
<br>
                <div class="table100 ver1 m-b-110">
                    <table data-vertable="ver1">
                        <thead>
                        <tr class="row100 head">
                            <th class="column100 column1" data-column="column1"></th>
                            <th class="column100 column2" data-column="column2"></th>

                        </thead>
                        <tbody>
                        <tr class="row100">
                            <td class="column100 column1" data-column="column1">{% trans %}Title{% endtrans %}</td>
                            <td class="column100 column2" data-column="column2">{{ task.title }}</td>

                        </tr>

                        <tr class="row100">
                            <td class="column100 column1" data-column="column1">{% trans %}Description{% endtrans %}</td>
                            <td class="column100 column2" data-column="column2">{{ task.description }}</td>

                        </tr>

                        <tr class="row100">
                            <td class="column100 column1" data-column="column1">{% trans %}Start hour{% endtrans %}</td>
                            <td class="column100 column2" data-column="column2">{{ task.starthour ? task.starthour|date('Y-m-d H:i:s') : '' }}</td>

                        </tr>

                        <tr class="row100">
                            <td class="column100 column1" data-column="column1">{% trans %}End hour{% endtrans %}</td>
                            <td class="column100 column2" data-column="column2">{{ task.endhour ? task.endhour|date('Y-m-d H:i:s') : '' }}</td>

                        </tr>

                        <tr class="row100">
                            <td class="column100 column1" data-column="column1">{% trans %}Created at{% endtrans %}</td>
                            <td class="column100 column2" data-column="column2">{{ task.createdat ? task.createdat|date('Y-m-d H:i:s') : '' }}</td>

                        </tr>

                        <tr class="row100">

                                     <td class="column100 column1" data-column="column1">{% trans %}participants{% endtrans %}</td>
                            <td class="column100 column2" data-column="column2"> {% for participant in task.userTasks %}
                                    {% if participant.user %}

                                        {{ participant.user.username }}<br>
                                    {% endif %}

                                {% endfor %}</td>

                        </tr>


                        </tbody>

                    </table>
                </div>

                    {% for i in selectprime %}

                        {% if i.task.id == task.id and i.isCreator %}
                                <button type="button" class="btn "><a href="{{ path('user_front_edit', {'id': task.id}) }}">{% trans %}edit{% endtrans %}</a></button>
                            &nbsp
                            <button id="l">{{ include('front/_delete_form.html.twig') }}</button>

                        {% endif %}
                    {% endfor %}

            </div>
        </div>

    </div>

    {#end new template#}







{% endblock %}